<?php
/**
 * Les 114 sourates et les riwayat.
 *
 * GENERE par outils/generer_sourates.py depuis donnees/suwar_*.json
 * (instantane de l'API publique mp3quran.net v3). Ne pas editer a la
 * main : relancer le script, puis outils/tests.py qui recompare.
 *
 * ar = nom arabe, tr = translitteration, fr = sens du titre en francais,
 * mek = 1 si mecquoise, 0 si medinoise, p1/p2 = pages du moushaf.
 */

if ( ! defined( 'ABSPATH' ) ) { exit; }

function huitcoran_sourates() {
	return array(
		1 => array('ar' => 'الفاتحة', 'tr' => 'Al-Fatihah', 'fr' => 'Prologue', 'mek' => 1, 'p1' => 1, 'p2' => 1),
		2 => array('ar' => 'البقرة', 'tr' => 'Al-Baqarah', 'fr' => 'La génisse', 'mek' => 0, 'p1' => 2, 'p2' => 49),
		3 => array('ar' => 'آل عمران', 'tr' => 'Aal Imran', 'fr' => 'La famille d\'Imran', 'mek' => 0, 'p1' => 50, 'p2' => 76),
		4 => array('ar' => 'النساء', 'tr' => 'An-Nisa\'', 'fr' => 'Les femmes', 'mek' => 0, 'p1' => 77, 'p2' => 106),
		5 => array('ar' => 'المائدة', 'tr' => 'Al-Ma\'idah', 'fr' => 'La table servie', 'mek' => 0, 'p1' => 106, 'p2' => 127),
		6 => array('ar' => 'الأنعام', 'tr' => 'Al-An\'am', 'fr' => 'Les bestiaux', 'mek' => 1, 'p1' => 128, 'p2' => 150),
		7 => array('ar' => 'الأعراف', 'tr' => 'Al-A\'raf', 'fr' => 'Al-A’raf', 'mek' => 1, 'p1' => 151, 'p2' => 176),
		8 => array('ar' => 'الأنفال', 'tr' => 'Al-Anfal', 'fr' => 'Le butin', 'mek' => 0, 'p1' => 177, 'p2' => 186),
		9 => array('ar' => 'التوبة', 'tr' => 'At-Taubah', 'fr' => 'Le repentir', 'mek' => 0, 'p1' => 187, 'p2' => 207),
		10 => array('ar' => 'يونس', 'tr' => 'Yunus', 'fr' => 'Jonas', 'mek' => 1, 'p1' => 208, 'p2' => 221),
		11 => array('ar' => 'هود', 'tr' => 'Hood', 'fr' => 'Hud', 'mek' => 1, 'p1' => 221, 'p2' => 235),
		12 => array('ar' => 'يوسف', 'tr' => 'Yusuf', 'fr' => 'Joseph', 'mek' => 1, 'p1' => 235, 'p2' => 248),
		13 => array('ar' => 'الرعد', 'tr' => 'Ar-Ra\'d', 'fr' => 'Le tonnerre', 'mek' => 0, 'p1' => 249, 'p2' => 255),
		14 => array('ar' => 'إبراهيم', 'tr' => 'Ibrahim', 'fr' => 'Abraham', 'mek' => 1, 'p1' => 255, 'p2' => 261),
		15 => array('ar' => 'الحجر', 'tr' => 'Al-Hijr', 'fr' => 'Al-Hijr', 'mek' => 1, 'p1' => 262, 'p2' => 267),
		16 => array('ar' => 'النحل', 'tr' => 'An-Nahl', 'fr' => 'Les abeilles', 'mek' => 1, 'p1' => 267, 'p2' => 281),
		17 => array('ar' => 'الإسراء', 'tr' => 'Al-Isra', 'fr' => 'Le voyage nocturne', 'mek' => 1, 'p1' => 282, 'p2' => 293),
		18 => array('ar' => 'الكهف', 'tr' => 'Al-Kahf', 'fr' => 'La caverne', 'mek' => 1, 'p1' => 293, 'p2' => 304),
		19 => array('ar' => 'مريم', 'tr' => 'Maryam', 'fr' => 'Marie', 'mek' => 1, 'p1' => 305, 'p2' => 312),
		20 => array('ar' => 'طه', 'tr' => 'Ta­Ha', 'fr' => 'Tâ-Hâ', 'mek' => 1, 'p1' => 312, 'p2' => 321),
		21 => array('ar' => 'الأنبياء', 'tr' => 'Al-Anbiya\'', 'fr' => 'Les prophètes', 'mek' => 1, 'p1' => 322, 'p2' => 331),
		22 => array('ar' => 'الحج', 'tr' => 'Al-Hajj', 'fr' => 'Le pèlerinage', 'mek' => 0, 'p1' => 332, 'p2' => 341),
		23 => array('ar' => 'المؤمنون', 'tr' => 'Al-Mu\'minun', 'fr' => 'Les croyants', 'mek' => 1, 'p1' => 342, 'p2' => 349),
		24 => array('ar' => 'النور', 'tr' => 'An-Nur', 'fr' => 'La lumière', 'mek' => 0, 'p1' => 350, 'p2' => 359),
		25 => array('ar' => 'الفرقان', 'tr' => 'Al-Furqan', 'fr' => 'Le discernement', 'mek' => 1, 'p1' => 359, 'p2' => 366),
		26 => array('ar' => 'الشعراء', 'tr' => 'Ash-Shu\'ara\'', 'fr' => 'Les poètes', 'mek' => 1, 'p1' => 367, 'p2' => 376),
		27 => array('ar' => 'النمل', 'tr' => 'An-Naml', 'fr' => 'Les fourmis', 'mek' => 1, 'p1' => 377, 'p2' => 385),
		28 => array('ar' => 'القصص', 'tr' => 'Al-Qasas', 'fr' => 'Le rècit', 'mek' => 1, 'p1' => 385, 'p2' => 396),
		29 => array('ar' => 'العنكبوت', 'tr' => 'Al-\'Ankabut', 'fr' => 'L\'araignèe', 'mek' => 1, 'p1' => 396, 'p2' => 404),
		30 => array('ar' => 'الروم', 'tr' => 'Ar­Room', 'fr' => 'Les romains', 'mek' => 1, 'p1' => 404, 'p2' => 410),
		31 => array('ar' => 'لقمان', 'tr' => 'Luqman', 'fr' => 'Louqmane', 'mek' => 1, 'p1' => 411, 'p2' => 414),
		32 => array('ar' => 'السجدة', 'tr' => 'As­Sajdah', 'fr' => 'La prosternation', 'mek' => 1, 'p1' => 415, 'p2' => 417),
		33 => array('ar' => 'الأحزاب', 'tr' => 'Al­Ahzab', 'fr' => 'Les coalisés', 'mek' => 0, 'p1' => 418, 'p2' => 427),
		34 => array('ar' => 'سبأ', 'tr' => 'Saba\'', 'fr' => 'Sabaa', 'mek' => 1, 'p1' => 428, 'p2' => 434),
		35 => array('ar' => 'فاطر', 'tr' => 'Fatir', 'fr' => 'Le Créateur', 'mek' => 1, 'p1' => 434, 'p2' => 440),
		36 => array('ar' => 'يس', 'tr' => 'Ya­Sin', 'fr' => 'Ya-Sin', 'mek' => 1, 'p1' => 440, 'p2' => 445),
		37 => array('ar' => 'الصافات', 'tr' => 'As-Saffat', 'fr' => 'Les rangés', 'mek' => 1, 'p1' => 446, 'p2' => 452),
		38 => array('ar' => 'ص', 'tr' => 'Sad', 'fr' => 'Sâd', 'mek' => 1, 'p1' => 453, 'p2' => 458),
		39 => array('ar' => 'الزمر', 'tr' => 'Az-Zumar', 'fr' => 'Les groupes', 'mek' => 1, 'p1' => 458, 'p2' => 467),
		40 => array('ar' => 'غافر', 'tr' => 'Ghafir', 'fr' => 'Le pardonneur', 'mek' => 1, 'p1' => 467, 'p2' => 476),
		41 => array('ar' => 'فصلت', 'tr' => 'Fussilat', 'fr' => 'Les versets détaillés', 'mek' => 1, 'p1' => 477, 'p2' => 482),
		42 => array('ar' => 'الشورى', 'tr' => 'Ash-Shura', 'fr' => 'La consultation', 'mek' => 1, 'p1' => 483, 'p2' => 489),
		43 => array('ar' => 'الزخرف', 'tr' => 'Az-Zukhruf', 'fr' => 'L\'ornement', 'mek' => 1, 'p1' => 489, 'p2' => 495),
		44 => array('ar' => 'الدّخان', 'tr' => 'Ad-Dukhan', 'fr' => 'La fumée', 'mek' => 1, 'p1' => 496, 'p2' => 498),
		45 => array('ar' => 'الجاثية', 'tr' => 'Al-Jathiya', 'fr' => 'L\'agenouillée', 'mek' => 1, 'p1' => 499, 'p2' => 502),
		46 => array('ar' => 'الأحقاف', 'tr' => 'Al-Ahqaf', 'fr' => 'Al-Ahqâf', 'mek' => 1, 'p1' => 502, 'p2' => 506),
		47 => array('ar' => 'محمد', 'tr' => 'Muhammad', 'fr' => 'Mohammed', 'mek' => 0, 'p1' => 507, 'p2' => 510),
		48 => array('ar' => 'الفتح', 'tr' => 'Al-Fath', 'fr' => 'La victoire éclatante', 'mek' => 0, 'p1' => 511, 'p2' => 515),
		49 => array('ar' => 'الحجرات', 'tr' => 'Al-Hujurat', 'fr' => 'Les appartements', 'mek' => 0, 'p1' => 515, 'p2' => 517),
		50 => array('ar' => 'ق', 'tr' => 'Qaf', 'fr' => 'Qâf', 'mek' => 1, 'p1' => 518, 'p2' => 520),
		51 => array('ar' => 'الذاريات', 'tr' => 'Az-Zariyat', 'fr' => 'Qui éparpillent', 'mek' => 1, 'p1' => 520, 'p2' => 523),
		52 => array('ar' => 'الطور', 'tr' => 'At-Tur', 'fr' => 'At-Tûr', 'mek' => 1, 'p1' => 523, 'p2' => 525),
		53 => array('ar' => 'النجم', 'tr' => 'An-Najm', 'fr' => 'L\'étoile', 'mek' => 1, 'p1' => 526, 'p2' => 528),
		54 => array('ar' => 'القمر', 'tr' => 'Al-Qamar', 'fr' => 'La lune', 'mek' => 1, 'p1' => 528, 'p2' => 531),
		55 => array('ar' => 'الرحمن', 'tr' => 'Ar-Rahman', 'fr' => 'Le Tout Miséricordieux', 'mek' => 0, 'p1' => 531, 'p2' => 534),
		56 => array('ar' => 'الواقعة', 'tr' => 'Al-Waqi\'ah', 'fr' => 'L\'evénement', 'mek' => 1, 'p1' => 534, 'p2' => 537),
		57 => array('ar' => 'الحديد', 'tr' => 'Al-Hadid', 'fr' => 'Le fer', 'mek' => 0, 'p1' => 537, 'p2' => 541),
		58 => array('ar' => 'المجادلة', 'tr' => 'Al-Mujadilah', 'fr' => 'La discussion', 'mek' => 0, 'p1' => 542, 'p2' => 545),
		59 => array('ar' => 'الحشر', 'tr' => 'Al-Hashr', 'fr' => 'L\'exode', 'mek' => 0, 'p1' => 545, 'p2' => 548),
		60 => array('ar' => 'الممتحنة', 'tr' => 'Al-Mumtahinah', 'fr' => 'L\'éprouvée', 'mek' => 0, 'p1' => 549, 'p2' => 551),
		61 => array('ar' => 'الصف', 'tr' => 'As-Saff', 'fr' => 'Le rang', 'mek' => 0, 'p1' => 551, 'p2' => 552),
		62 => array('ar' => 'الجمعة', 'tr' => 'Al-Jumu\'ah', 'fr' => 'Le vendredi', 'mek' => 0, 'p1' => 553, 'p2' => 554),
		63 => array('ar' => 'المنافقون', 'tr' => 'Al-Munafiqun', 'fr' => 'Les hypocrites', 'mek' => 0, 'p1' => 554, 'p2' => 555),
		64 => array('ar' => 'التغابن', 'tr' => 'At-Taghabun', 'fr' => 'La grande perte', 'mek' => 0, 'p1' => 556, 'p2' => 557),
		65 => array('ar' => 'الطلاق', 'tr' => 'At-Talaq', 'fr' => 'Le divorce', 'mek' => 0, 'p1' => 558, 'p2' => 559),
		66 => array('ar' => 'التحريم', 'tr' => 'At-Tahrim', 'fr' => 'L\'interdiction', 'mek' => 0, 'p1' => 560, 'p2' => 561),
		67 => array('ar' => 'الملك', 'tr' => 'Al-Mulk', 'fr' => 'La royauté', 'mek' => 1, 'p1' => 562, 'p2' => 564),
		68 => array('ar' => 'القلم', 'tr' => 'Al-Qalam', 'fr' => 'La plume', 'mek' => 1, 'p1' => 564, 'p2' => 566),
		69 => array('ar' => 'الحاقة', 'tr' => 'Al-Haqqah', 'fr' => 'Celle qui montre la vérité', 'mek' => 1, 'p1' => 566, 'p2' => 568),
		70 => array('ar' => 'المعارج', 'tr' => 'Al-Ma\'arij', 'fr' => 'Les voies d\'ascension', 'mek' => 1, 'p1' => 568, 'p2' => 570),
		71 => array('ar' => 'نوح', 'tr' => 'Nooh', 'fr' => 'Noé', 'mek' => 1, 'p1' => 570, 'p2' => 571),
		72 => array('ar' => 'الجن', 'tr' => 'Al-Jinn', 'fr' => 'Les djinns', 'mek' => 1, 'p1' => 572, 'p2' => 573),
		73 => array('ar' => 'المزمل', 'tr' => 'Al-Muzzammil', 'fr' => 'L\'enveloppé', 'mek' => 1, 'p1' => 574, 'p2' => 575),
		74 => array('ar' => 'المدثر', 'tr' => 'Al-Muddaththir', 'fr' => 'Le revêtu d\'un manteau', 'mek' => 1, 'p1' => 575, 'p2' => 577),
		75 => array('ar' => 'القيامة', 'tr' => 'Al-Qiyamah', 'fr' => 'La résurrection', 'mek' => 1, 'p1' => 577, 'p2' => 578),
		76 => array('ar' => 'الإنسان', 'tr' => 'Al-Insan', 'fr' => 'L\'homme', 'mek' => 0, 'p1' => 578, 'p2' => 580),
		77 => array('ar' => 'المرسلات', 'tr' => 'Al-Mursalat', 'fr' => 'Les envoyés', 'mek' => 1, 'p1' => 580, 'p2' => 581),
		78 => array('ar' => 'النبأ', 'tr' => 'An-Naba\'', 'fr' => 'La nouvelle', 'mek' => 1, 'p1' => 582, 'p2' => 583),
		79 => array('ar' => 'النازعات', 'tr' => 'An-Nazi\'at', 'fr' => 'Les Anges qui arrachent les âm', 'mek' => 1, 'p1' => 583, 'p2' => 584),
		80 => array('ar' => 'عبس', 'tr' => 'Abasa', 'fr' => 'Il s\'est renfrogné', 'mek' => 1, 'p1' => 585, 'p2' => 586),
		81 => array('ar' => 'التكوير', 'tr' => 'At-Takwir', 'fr' => 'L\'obscurcissement', 'mek' => 1, 'p1' => 586, 'p2' => 586),
		82 => array('ar' => 'الإنفطار', 'tr' => 'Al-Infitar', 'fr' => 'La rupture', 'mek' => 1, 'p1' => 587, 'p2' => 587),
		83 => array('ar' => 'المطففين', 'tr' => 'Al-Mutaffifin', 'fr' => 'Les fraudeurs', 'mek' => 1, 'p1' => 587, 'p2' => 589),
		84 => array('ar' => 'الإنشقاق', 'tr' => 'Al-Inshiqaq', 'fr' => 'La déchirure', 'mek' => 1, 'p1' => 589, 'p2' => 590),
		85 => array('ar' => 'البروج', 'tr' => 'Al-Buruj', 'fr' => 'Les constellations', 'mek' => 1, 'p1' => 590, 'p2' => 590),
		86 => array('ar' => 'الطارق', 'tr' => 'At-Tariq', 'fr' => 'L\'astre nocturne', 'mek' => 1, 'p1' => 591, 'p2' => 591),
		87 => array('ar' => 'الأعلى', 'tr' => 'Al-A\'la', 'fr' => 'Le Très-Haut', 'mek' => 1, 'p1' => 591, 'p2' => 592),
		88 => array('ar' => 'الغاشية', 'tr' => 'Al-Ghashiyah', 'fr' => 'L\'enveloppante', 'mek' => 1, 'p1' => 592, 'p2' => 593),
		89 => array('ar' => 'الفجر', 'tr' => 'Al-Fajr', 'fr' => 'L\'aube', 'mek' => 1, 'p1' => 593, 'p2' => 594),
		90 => array('ar' => 'البلد', 'tr' => 'Al-Balad', 'fr' => 'La cité', 'mek' => 1, 'p1' => 594, 'p2' => 595),
		91 => array('ar' => 'الشمس', 'tr' => 'Ash-Shams', 'fr' => 'Le soleil', 'mek' => 1, 'p1' => 595, 'p2' => 595),
		92 => array('ar' => 'الليل', 'tr' => 'Al-Lail', 'fr' => 'La nuit', 'mek' => 1, 'p1' => 595, 'p2' => 596),
		93 => array('ar' => 'الضحى', 'tr' => 'Ad-Duha', 'fr' => 'Le jour montant', 'mek' => 1, 'p1' => 596, 'p2' => 596),
		94 => array('ar' => 'الشرح', 'tr' => 'Ash-Sharh', 'fr' => 'L\'ouverture', 'mek' => 1, 'p1' => 596, 'p2' => 597),
		95 => array('ar' => 'التين', 'tr' => 'At-Tin', 'fr' => 'Le figuier', 'mek' => 1, 'p1' => 597, 'p2' => 597),
		96 => array('ar' => 'العلق', 'tr' => 'Al-\'Alaq', 'fr' => 'L\'adhérence', 'mek' => 1, 'p1' => 597, 'p2' => 598),
		97 => array('ar' => 'القدر', 'tr' => 'Al-Qadr', 'fr' => 'La Destinée', 'mek' => 1, 'p1' => 598, 'p2' => 598),
		98 => array('ar' => 'البينة', 'tr' => 'Al-Baiyinah', 'fr' => 'La preuve', 'mek' => 0, 'p1' => 598, 'p2' => 599),
		99 => array('ar' => 'الزلزلة', 'tr' => 'Az-Zalzalah', 'fr' => 'La secousse', 'mek' => 0, 'p1' => 599, 'p2' => 599),
		100 => array('ar' => 'العاديات', 'tr' => 'Al-\'Adiyat', 'fr' => 'Les coursiers', 'mek' => 1, 'p1' => 599, 'p2' => 600),
		101 => array('ar' => 'القارعة', 'tr' => 'Al-Qari\'ah', 'fr' => 'Le fracas', 'mek' => 1, 'p1' => 600, 'p2' => 600),
		102 => array('ar' => 'التكاثر', 'tr' => 'At-Takathur', 'fr' => 'La course aux richesses', 'mek' => 1, 'p1' => 600, 'p2' => 600),
		103 => array('ar' => 'العصر', 'tr' => 'Al-\'Asr', 'fr' => 'Le temps', 'mek' => 1, 'p1' => 601, 'p2' => 601),
		104 => array('ar' => 'الهمزة', 'tr' => 'Al-Humazah', 'fr' => 'Les calomniateurs', 'mek' => 1, 'p1' => 601, 'p2' => 601),
		105 => array('ar' => 'الفيل', 'tr' => 'Al-Fil', 'fr' => 'L\'éléphant', 'mek' => 1, 'p1' => 601, 'p2' => 601),
		106 => array('ar' => 'قريش', 'tr' => 'Quraish', 'fr' => 'Qoraïsh', 'mek' => 1, 'p1' => 602, 'p2' => 602),
		107 => array('ar' => 'الماعون', 'tr' => 'Al-Ma\'un', 'fr' => 'L\'ustensile', 'mek' => 1, 'p1' => 602, 'p2' => 602),
		108 => array('ar' => 'الكوثر', 'tr' => 'Al-Kauthar', 'fr' => 'L\'abondance', 'mek' => 1, 'p1' => 602, 'p2' => 602),
		109 => array('ar' => 'الكافرون', 'tr' => 'Al-Kafirun', 'fr' => 'Les infidèles', 'mek' => 1, 'p1' => 603, 'p2' => 603),
		110 => array('ar' => 'النصر', 'tr' => 'An-Nasr', 'fr' => 'Les secours', 'mek' => 0, 'p1' => 603, 'p2' => 603),
		111 => array('ar' => 'المسد', 'tr' => 'Al-Masad', 'fr' => 'Les fibres', 'mek' => 1, 'p1' => 603, 'p2' => 603),
		112 => array('ar' => 'الإخلاص', 'tr' => 'Al-Ikhlas', 'fr' => 'Le monothéisme pur', 'mek' => 1, 'p1' => 604, 'p2' => 604),
		113 => array('ar' => 'الفلق', 'tr' => 'Al-Falaq', 'fr' => 'L\'aube naissante', 'mek' => 1, 'p1' => 604, 'p2' => 604),
		114 => array('ar' => 'الناس', 'tr' => 'An-Nas', 'fr' => 'Les hommes', 'mek' => 1, 'p1' => 604, 'p2' => 604),
	);
}

function huitcoran_riwayat() {
	return array(
		1 => 'Rewayat Hafs A\'n Assem',
		2 => 'Rewayat Warsh A\'n Nafi\'',
		3 => 'Rewayat Khalaf A\'n Hamzah',
		4 => 'Rewayat Albizi A\'n Ibn Katheer',
		5 => 'Rewayat Qalon A\'n Nafi\'',
		6 => 'Rewayat Qunbol A\'n Ibn Katheer',
		7 => 'Rewayat Assosi A\'n Abi Amr',
		8 => 'Rewayat Qalon A\'n Nafi\' Men Tariq Abi Nasheet',
		9 => 'Rewayat Rowis and Rawh A\'n Yakoob Al Hadrami ',
		10 => 'Rewayat Warsh A\'n Nafi\' Men  Tariq Abi Baker Alasbahani',
		11 => 'Rewayat Albizi and Qunbol A\'n Ibn Katheer',
		12 => 'Rewayat AlDorai A\'n Al-Kisa\'ai',
		13 => 'Rewayat Aldori A\'n Abi Amr',
		15 => 'Sho\'bah A\'n Asim',
		16 => 'Ibn Thakwan A\'n Ibn Amer',
		18 => 'Rewayat Warsh A\'n Nafi\' Men Tariq Alazraq',
		19 => 'Hesham A\'n Abi A\'mer',
		20 => 'Ibn Jammaz A\'n Abi Ja\'far',
		21 => 'Educateur',
		22 => 'Almusshaf Al Mojawwad',
	);
}
